config/routes.rb
Rails.application.routes.draw do
  # pwa routes
  get '/service-worker.js' => "service_worker#service_worker"
  get '/manifest.json' => "service_worker#manifest"
  get '/privacy-policy' => 'static_pages#privacy'
  devise_for :users, :controllers => {registrations: "registrations", omniauth_callbacks: 'omni_auth'}

  get 'users/index'
  get 'friends', to: 'friendships#index'
  get 'notifications', to: 'notifications#index'
  resources :posts, except: [:new, :edit, :update]
  resources :comments, except: [:new, :edit, :update, :show, :destory]
  resources :likes, except: [:edit, :update, :show, :new]
  resources :friendships
  authenticated :user do
    root to: 'posts#index', as: :authenticated_root
  end
  root 'static_pages#home'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :friendships, dependent: :destroy
  has_many :friends,
           -> { where friendships: { status: 'accepted' } }, through: :friendships
  has_many :pending_friends,
           -> { where friendships: { status: 'pending' } }, through: :friendships, source: :friend
  has_many :requested_friends,
           -> { where friendships: { status: 'requested' } }, through: :friendships, source: :friend
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  validates :first_name, presence: true
  validates :last_name, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.img_link = auth.info.image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info'])
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def display_name
    first_name + ' ' + last_name
  end

  def initial
    first_name[0].upcase
  end

  def my_timeline_posts
    Post.where(user_id: self).or(Post.where(user_id: friends))
  end

  def friend_request(friend)
    friendships.create(friend: friend, status: 'pending')
    friend.friendships.create(friend: self, status: 'requested')
  end

  def accept(friend)
    pending_relations(friend).each { |friendship| friendship.update(status: 'accepted') }
  end

  def pending_relations(friend)
    Friendship.where(user: self, friend: friend) + Friendship.where(user: friend, friend: self)
  end

  def relations(friend)
    Friendship.where(user: self,
                     friend: friend,
                     status: 'accepted') + Friendship.where(user: friend,
                                                            friend: self,
                                                            status: 'accepted')
  end

  def friend_with?(friend)
    Friendship.where(user: self, friend: friend, status: 'accepted').any?
  end

  def decline_request(friend)
    relations(friend).each(&:destroy)
  end

  def strangers
    User.all - [self] - friends - pending_friends - requested_friends
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all - [current_user] - current_user.friends
  end
end

app/views/users/_user_card.html.erb
<div class="do-sidebar d-flex flex-column justify-content-center align-items-center">
    <% if current_user.img_link.nil? %>
        <div class="profile-img--default m-4"><%= current_user_initial %></div>
    <%else%>
        <%= image_tag current_user.img_link, class:"profile-img m-4"%>  
    <%end%>
    <p><%= current_user.display_name%></p>
    <p class="sub-title"><%= current_user.email %></p>

</div>
<div class="d-flex justify-content-between m-3">
    <%= link_to 'Friends', friends_path, class: 'do-btn'%>
    <%= link_to 'Notifications', notifications_path, class: 'do-btn'%>
</div>

app/views/users/index.html.erb
<nav class="navbar">
  <svg class="brand-logo" width="80" height="80" viewBox="0 0 80 80" fill="none" xmlns="http://www.w3.org/2000/svg">
    <circle cx="40" cy="40" r="35" fill="black" stroke="#00BAF4" stroke-width="10" />
    <path
      d="M20.1602 42.3496C20.1602 39.3848 20.8223 37.0234 22.1465 35.2656C23.4824 33.5078 25.3047 32.6289 27.6133 32.6289C29.4648 32.6289 30.9941 33.3203 32.2012 34.7031V25H37.2988V52H32.7109L32.4648 49.9785C31.1992 51.5605 29.5703 52.3516 27.5781 52.3516C25.3398 52.3516 23.541 51.4727 22.1816 49.7148C20.834 47.9453 20.1602 45.4902 20.1602 42.3496ZM25.2402 42.7188C25.2402 44.5 25.5508 45.8652 26.1719 46.8145C26.793 47.7637 27.6953 48.2383 28.8789 48.2383C30.4492 48.2383 31.5566 47.5762 32.2012 46.252V38.7461C31.5684 37.4219 30.4727 36.7598 28.9141 36.7598C26.4648 36.7598 25.2402 38.7461 25.2402 42.7188ZM40.4453 42.3145C40.4453 40.4277 40.8086 38.7461 41.5352 37.2695C42.2617 35.793 43.3047 34.6504 44.6641 33.8418C46.0352 33.0332 47.623 32.6289 49.4277 32.6289C51.9941 32.6289 54.0859 33.4141 55.7031 34.9844C57.332 36.5547 58.2402 38.6875 58.4277 41.3828L58.4629 42.6836C58.4629 45.6016 57.6484 47.9453 56.0195 49.7148C54.3906 51.4727 52.2051 52.3516 49.4629 52.3516C46.7207 52.3516 44.5293 51.4727 42.8887 49.7148C41.2598 47.957 40.4453 45.5664 40.4453 42.543V42.3145ZM45.5254 42.6836C45.5254 44.4883 45.8652 45.8711 46.5449 46.832C47.2246 47.7812 48.1973 48.2559 49.4629 48.2559C50.6934 48.2559 51.6543 47.7871 52.3457 46.8496C53.0371 45.9004 53.3828 44.3887 53.3828 42.3145C53.3828 40.5449 53.0371 39.1738 52.3457 38.2012C51.6543 37.2285 50.6816 36.7422 49.4277 36.7422C48.1855 36.7422 47.2246 37.2285 46.5449 38.2012C45.8652 39.1621 45.5254 40.6562 45.5254 42.6836Z"
      fill="white" />
  </svg>
  <ul>
    <%= link_to "Feed", root_path, class: 'do-btn' %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'do-btn' %>
  </ul>
</nav>

<section class="container col-md-6">
  <h3 class="title text-primary">DEVS AROUND YOU</h3>
  <% if @users.empty? %>
      <%= render 'shared/if_empty_text', {page: 'devs around you'}%>
  <%else%>  
      <% @users.each do |user| %>
      <div class="user-card d-sm-flex align-items-center m-3 justify-content-between">
        <div class="d-sm-flex align-items-center">
          <% if user.img_link.nil? %>
              <div class="profile-img--default m-3"><%= user.initial %></div>
          <%else%>
              <%= image_tag user.img_link, class:"profile-img m-3"%>  
          <%end%>
          <div>
            <%= user.display_name%> <br>
            <%= user.email%>
            <%if !current_user.relations(user).count.zero? %> 
            <br>
            <small><%= current_user.relations(user).count %> mutual friends</small>
            <%end%>
          </div>
        </div>
        <%if current_user.pending_friends.include?(user)%>
          <%= 'request pending'%>
        <%else%>
          <%= link_to show_svg('general_icons/add_friend.svg'), friendships_path({user_id: user.id}), method: 'post', class: 'friend-request-btn'%>
        <%end%>
      </div>
      <%end%>
  <%end%>
</section>